// BannerComponent as initially generated by the CLI
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-banner-initial',
  template: `<p>banner works!</p>`,
  styles: []
})
export class BannerInitialComponent { }

